version: '3'
services:

  # PHP Service
  app:
    build:
      context: ..
      dockerfile: ./docker/images/php/Dockerfile
    image: digitalocean.com/php
    container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ..:/var/www:delegated
      - ./images/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    expose:
      - 9000
    networks:
      - app-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../:/var/www
      - ./images/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: torrents
      MYSQL_ROOT_PASSWORD: torrents
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./images/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - WEBUI_PORT=8080
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ./images/qBittorrent/config/qBittorrent.conf:/config/qBittorrent/qBittorrent_new.conf
      - ./../media/:/downloads/
    networks:
      - app-network

  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    tty: true
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ALLOWED_NETWORKS=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8
    ports:
      - 32400:32400
    volumes:
      - ./../media:/data
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local